[[constraint]]
  branch = "master"
  name = "github.com/apex/log"

[[constraint]]
  branch = "master"
  name = "github.com/jinzhu/configor"

[[constraint]]
  branch = "master"
  name = "github.com/streadway/amqp"
